


<?php echo $topview; ?>
<?php echo $navigation; ?>


<div class="row-fluid">
    <div class="span3 attraction_category">
        <?php echo $category; ?>
    </div>
    <div class="span7">
        <div class="attraction_grid">
            <h3>Достопримечательности города Ялты</h3>
            <ul class="grid_attraction cs-style-2">
                <?php foreach($attractions as $attraction) :?>
                    <li>
                        <figure>
                            <img width="400" height="100" class="main-image" src="<?php echo $this->basePath(). $this->escapeHtml($attraction->attraction_main_photo);?>"/>
                            <figcaption>
                                <a href="<?php echo $this->url('attraction',
                                    array('action'=>'attraction', 'attraction_id_name' => $attraction->attraction_id_name));?>"><?php echo $this->escapeHtml($attraction->attraction_name); ?></a><br/>
                                     <span><b>Адресc:</b>   <span><?php echo $this->escapeHtml($attraction->attraction_address); ?></span>
                                        <button class="button button-attraction-1" id="green">
                                            Проложить маршрут
                                        </button><br/>
                                         <button class="button button-attraction-1" id="red" onclick="">
                                            Добавить в маршрут
                                         </button>
                            </figcaption>
                        </figure>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>