<ul class="nav nav-tabs nav-stacked">
<!--    <li><a href="--><?php //echo $this->url('attractions'); ?><!--">Достопримечательности</a></li>-->
    <li><a href="<?php echo $this->url('attractions'); ?>">Достопримечательности</a></li>
    <li><a>Маршруты</a></li>
    <li><a>Транспорт</a></li>
    <li><a href="<?php echo $this->url('restaurants'); ?>">Рестораны</a></li>
    <li><a>Кафе</a></li>
    <li><a>Клубы</a></li>
    <li><a>Развлечения</a></li>
    <li><a>Шопинг</a></li>
    <li><a>Здоровье и спорт</a></li>
    <li><a href="<?php echo $this->url('hostels'); ?>">Гостиницы и минигостиницы</a></li>
    <li><a>Частный сектор</a></li>
    <li><a>Справочные и аварийные службы</a></li>
    <li><a>Статьи</a></li>
    <li><a>Афиша</a></li>
    <li><a>Геолокации</a></li>
</ul>