<div class="dropdown filter">
    <h1 class="dropdown-toggle" data-toggle="dropdown" href="#">Выберите тип заведения</h1>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a  onclick="initialize();"  id="attraction_filter">Достопримечательности</a></li>
        <li><a> Маршруты</a></li>
        <li><a>Клубы</a></li>
        <li><a>Развлечения</a></li>
        <li><a>Шопинг</a></li>
        <li><a>Здоровье и спорт</a></li>
        <li><a>Гостиницы и минигостиницы</a></li>
        <li><a>Частный сектор</a></li>
        <li><a>Справочные и аварийные службы</a></li>
        <li><a>Статьи</a></li>
        <li><a>Афиша</a></li>
        <li><a>Геолокации</a></li>
    </ul>
</div>