<div class="modal fade" id="map-modal">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Маршрут&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" id="route-map-button" class="position-type-link active">карта</a>&nbsp;&nbsp;&nbsp;<a href="#" id="route-desc-button" class="position-type-link">описание маршрута</a></h3>
    </div>
    <div class="modal-body">
        <div id="route-map-container">
            <div class="label label-info" style="margin: 0 0 2px 0; text-align: center;">Можно изменить маршрут перетащив любую его точку в нужное место.</div>
            <div style="width: 530px; height: 350px;" id="google-map"></div>
        </div>
        <div id="route-desc-container" style="display: none">
            <div style="width: 530px; height: 360px; overflow: auto; border: 1px solid silver; border-radius: 3px; padding: 3px;" id="route-panel"></div>
        </div>
    </div>
    <div class="modal-footer">
        <div style="float: left; padding: 5px 0 0 0;">Расстояние: <span id="modal-distance">...</span></div>
        <a href="#" class="btn" data-dismiss="modal">Закрыть</a>
    </div>
</div>