<div class="row-fluid">

      <div class="span10 navigation_span">
            <div class="navbar">
                           <div class="navbar-inner">
                            <ul class="nav navigation">
                                <li><a href="<?php echo $this->url('attractions');?>"><? echo $this->translate('About us'); ?></a></li>
                                <li><a href="<?php echo $this->url('transport');?>"><? echo $this->translate('Articles'); ?></a></li>
                                <li><a href="<?php echo $this->url('restaurants');?>"><? echo $this->translate('Advertisers'); ?></a></li>
                                <li><a><? echo $this->translate('Tourists'); ?></a></li>
                                <li><a>Места MUST SEE</a></li>
                            </ul>
                        </div>
            </div>
      </div>
</div>
