<div class="row-fluid-topper">
    <div class="row-fluid head">
        <div class="span2">
            <a href="<?php echo $this->url('home');?>">
                <!--<img src="http://www.travelsmart.com.ua/images/ua-logos/32-logo-yalta.jpg" width="100" height="100" alt="Ялта">-->
                <img src="http://s-group.in.ua/yalta/public/img/logo1.png" width="130" height="115" alt="Ялта">
            </a>
        </div>
        <div class="span3">
            <ul>
                <li>
                    <!--<h3 style="font-family: 'asenine_cyrillicregular'; font-size: 15px;">8(495)771-73-12</h3>
                    <p>Заказ по телефону</p>-->
                    <p style="font-family: 'asenine_cyrillicregular'; font-size: 16px; color: #e61818; text-align:center; line-height: 16px;">Свяжитесь с нами:<br/>+38 093 1 1 1 1 1 1 1<br/>г Ялта, ул Замечательная 1</p>
                </li>
                <!--<li>
                    <h3>8(495)771-73-12</h3>
                    <p>Заказ по телефону</p>
                </li>
                <li>
                    <h3>8(800)700-00-10</h3>
                    <nobr>Круглосуточный заказ</nobr><br/>
                    <nobr>Звонок бесплатный</nobr>
                </li>-->
            </ul>
        </div>
        <div class="span4">
            <?php echo $this->rightside; ?>
        </div>
        <div class="span3 admin_panel">
            <div class="navbar-inner">
                <div class="nav navigation">
                    <li>
                        <a style="color:#009999;font-family:'asenine_cyrillicregular'" href="<?php echo $this->url('zfcuser/login'); ?>">Войти в админ.панель</a>
                    </li>
                </div>
            </div>
        </div>
    </div>
</div>