<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <ul class="nav right">
            <li>
                <a href="<?php echo $this->escapeHtml('user');?>" class="othercats_a othercats_hr">Авторизация</a>
            </li>
            <li>
                <a href="<?php echo $this->escapeHtml('admin')?>" class="othercats_a ">Админ.панель</a>
            </li>
            <li>
                <a href="/" class="othercats_a">Cкачать приложение для Android/IOS</a>
            </li>
        </ul>
    </div>
</div>
