<!-- main blocks -->
<?php echo $topline; ?>
<?php echo $topview; ?>
<?php echo $navigation; ?>
<!-- main blocks -->
<div class="span10 transport_road_minibus">
    <h1>Расписание всех маршруток города Ялта</h1>
</div>
<div class="span10 transport_road_minibus">

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Начальна точка маршрута</th>
            <th>Конечная точка маршрута</th>
            <th>Среднее время езды по этому маршруту</th>
            <th>Стоимость проезда</th>
            <th>Номер маршрутки</th>
            <th>Время работы маршрута</th>
            <th>Альтернативные маршруты</th>
        </tr>
        </thead>
        <tbody>
        <?php  foreach($shedule_road_minibus as $shedule) : ?>
            <tr>
                <td><?php echo $shedule->shedule_road_minibus_start_point; ?></td>
                <td><?php echo $shedule->shedule_road_minibus_end_point; ?></td>
                <td><?php echo $shedule->shedule_road_minibus_duration; ?></td>
                <td><?php echo $shedule->transport_road_minibus_price; ?></td>
                <td><?php echo $shedule->transport_road_minibus_model; ?></td>
                <td><?php echo $shedule->transport_road_minibus_time_work; ?></td>
                <td><?php echo $shedule->shedule_road_minibus_alternative_shedule; ?></td>
            </tr>
        <?php endforeach;  ?>
        </tbody>
    </table>
</div>