<?php echo $topview; ?>
<?php echo $navigation; ?>
<div class="row-fluid">
    <div class="span3 attraction_category">
        <?php echo $category; ?>
    </div>
    <div class="span7">
        <div class="restaurant_grid">
            <h3>Рестораны города Ялты</h3>
            <ul class="grid_restaurant cs-style-2">
                <?php foreach($restaurants as $restaurant) :?>

                    <li>
                        <figure>
                            <img width="450" height="100" class="main-image" src="<?php echo  $this->basePath() . substr($restaurant->restaurant_thumbnail,8); ?>" />
                            <figcaption>
                                <a href="<?php echo $this->url('restaurant',
                                    array('action'=>'restaurant', 'restaurant_id_name' => $restaurant->restaurant_id_name));?>"><?php echo $this->escapeHtml($restaurant->restaurant_name); ?></a><br/>
                                     <span><b>Адресc:</b>   <span><?php echo $this->escapeHtml($restaurant->restaurant_address); ?></span>
                                        <button class="button button-attraction-1" id="green">
                                            Проложить маршрут
                                        </button><br/>
                                         <button class="button button-attraction-1" id="red" onclick="">
                                             Добавить в маршрут
                                         </button>
                            </figcaption>
                        </figure>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>