<?php echo $topview; ?>
<?php echo $navigation; ?>
<div class="row-fluid">
    <div class="span3 attraction_category">
        <?php echo $category; ?>
    </div>
    <div class="span7">
        <div class="cafe_grid">
            <h3>Кафе города Ялты</h3>
            <ul class="grid_cafe cs-style-2">
                <?php foreach($cafes as $cafe) :?>
                    <li>
                        <figure>
                            <img width="450" height="100" class="main-image" src="<?php echo $this->basePath().  $this->escapeHtml($cafe->cafe_thumbnail);?>"/>
                            <figcaption>
                                <a href="<?php echo $this->url('cafe',
                                    array('action'=>'cafe', 'cafe_id_name' => $cafe->cafe_id_name));?>"><?php echo $this->escapeHtml($cafe->cafe_name); ?></a><br/>
                                     <span><b>Адресc:</b>   <span><?php echo $this->escapeHtml($cafe->cafe_address); ?></span>
                                        <button class="button button-attraction-1" id="green">
                                            Проложить маршрут
                                        </button><br/>
                                         <button class="button button-attraction-1" id="red" onclick="">
                                             Добавить в маршрут
                                         </button>
                            </figcaption>
                        </figure>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>