<ul class="nav nav-tabs nav-stacked attraction_detailed_information">
    <li>
       <h4>Время работы</h4>
       <a><?php echo $attraction->attraction_time_work; ?></a>
       <h4>Стоимость билета</h4>
       <a><?php echo $attraction->attraction_ticket_price; ?></a>
       <h4>Вид достопримечательности</h4>
       <a><?php echo $attraction->attraction_type; ?></a>
       <h4>Телефон</h4>
       <a><?php echo $attraction->attraction_telephone; ?></a>
       <h4>Адрес</h4>
       <a><?php echo $attraction->attraction_address; ?></a>
       <button  class="button button_attraction_detailed_information" id="green">
            <a href="<?php echo $attraction->attraction_site; ?>" style="color: #ffffff;cursor: pointer;text-decoration: none">Перейти на сайт</a>
       </button><br/>
       <button onclick="showRoute(<?php echo $attraction->attraction_latitude; ?>,<? echo $attraction->attraction_longitude; ?>);" class="button button_attraction_detailed_information" id="red" >
            Проложить маршрут
        </button>
    </li>
</ul>
