<div class="row-fluid attraction-menu">
    <div class="span8 navigation_span">
        <div class="navbar">
            <div class="navbar-inner">
                <ul class="nav navigation">
                    <li><a>Описание</a></li>
                    <li><a href="<?php echo $this->url('poster',
                            array('action'=>'attraction_poster', 'attraction_id_name' => $attraction->attraction_id_name));?>">Афиша</a></li>
                    <li><a>Акции</a></li>
                    <li><a>Фотоотчеты</a></li>
                    <li><a>Фото/видео</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>