<?php echo $topline; ?>
<?php echo $topview; ?>
<div class="container-fluid">
    <div class="attraction_main">
        <h1>Раздел клубы</h1>
    </div>
    <?php echo $navigation; ?>

    <div class="row-fluid attraction">

        <div class="restaurant_header">
            <h1><?php echo $club->club_name; ?></h1>
        </div>
        <div class="span3 attraction_main_image">
            <img width="300" src="<?php echo $this->basePath() . $club->club_thumbnail; ?>" class="img-polaroid">
            <?php
            $additional_images = explode(" ",$club->club_images);
            $count_additional_images  = count($additional_images);
            //                echo  $attraction->attraction_additional_photos;
            //                echo $count_additional_images;
            //                echo $additional_images[0];
            for($i =0; $i< $count_additional_images; $i++){ ?>
                <img width="90" src="<?php echo $this->basePath(). $additional_images[$i]; ?>" class="img-polaroid">
            <?
            }
            ?>
            <button class="button_to_favorites" id="green">
                В Избранное
            </button><br/><br/>
            <p>Растояние от вашего местоположения до <? echo $club->club_name; ?>  равно:  <i class="distance"></i> км </p>

            <? if($club->club_wifi == 1){ ?>

                     <img src="<?php echo $this->basePath(). "/img/features/wi-fi.png";?>"/>

           <? } ?>
            <? if($club->club_parking == 1){ ?>

                    <img src="<?php echo $this->basePath(). "/img/features/parking.png";?>"/>

            <? } ?>

        </div>
        <div class="span3 attraction_information">
            <?php echo $detailed_information; ?>
        </div>
        <div class="span4 attraction_map img-polaroid">
            <!-- google maps block -->
            <?php echo $map_attraction; ?>
            <!-- /google maps block -->
        </div>

        <div class="span6 attraction_description">
            <p> <?php echo $club->club_description; ?></p>
        </div>
        <div class="span4 cafe_other_objects">
            <ul class="grid_restaurant grid_attraction cs-style-2">
                <h3>Обьекты рядом</h3>
                <?php
                $current_club= $club->club_name;
                foreach($clubs as $club) :
                    if($current_club == $club->club_name) { continue; }
                    else
                    { ?>
                        <li>
                            <figure>
                                <img width="400" height="100" class="main-image" src="<?php echo $this->basePath(). $this->escapeHtml($cafe->club_thumbnail);?>"/>
                                <figcaption>
                                    <a href="<?php echo $this->url('club',
                                        array('action'=>'club', 'club_id_name' => $cafe->club_id_name));?>"><?php echo $this->escapeHtml($cafe->club_name); ?></a><br/>
                                             <span><b>Адресc:</b>   <span><?php echo $this->escapeHtml($club->club_address); ?></span>
                                                <button class="button button-attraction-1" id="green">
                                                    Проложить маршрут
                                                </button><br/>
                                                 <button class="button button-attraction-1" id="red" onclick="">
                                                     Добавить в маршрут
                                                 </button>
                                </figcaption>
                            </figure>
                        </li>
                    <?php  }
                endforeach; ?>
            </ul>
        </div>


    </div>
    <div class="row-fluid">
        <!-- http://twitter.github.io/bootstrap/base-css.html#tables -->
        <div class="span6">
                   <div class="attraction_disqus">
                        <h2>Оставьте ваш комментарий!</h2>
                        <div id="disqus_thread"></div>
                        <script type="text/javascript">
                            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                            var disqus_shortname = 'yaltapublic'; // required: replace example with your forum shortname

                            /* * * DON'T EDIT BELOW THIS LINE * * */
                            (function() {
                                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                            })();
                        </script>
                        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
                   </div>
        </div>
    </div>
</div>




