<?php echo $this->top; ?>
<!-- navigation block -->
<?php echo $this->navigation; ?>
<!--/navigation block -->
<div class="container-fluid">
    <div class="span4">
        <?php echo $this->categories; ?>
    </div>
    <div class="span7">
        <!-- google maps block -->
        <?php echo $this->google_maps; ?>
        <!-- /google maps block -->
        <?php echo $this->marker; ?>
    </div>
    <div class="buttonsocial">
        <a href="#" class="fly-button" id="facebook-button" target="_blank">Facebook</a>
    </div>
</div>
<div class="footer">
    <div class="infoot">


    </div>

</div>

<!--  modal block view-->
<?php //echo $this->modal_window; ?>
<!--  /modal block view-->

<!-- map modal block view -->
<?php /*?>  <?php echo $this->map_modal; ?><?php */?>

